description = "An AI-powered configuration for any project"
ignore = [
  "README.md",
  "template.toml",
]
kickstart_version = 1
name = "AI"

copy_without_render = [
  "*.sh",
]

post_gen_hooks = [
  {name = "setting up Serena", path = ".ai/hooks/index-serena.sh"},
  {name = "setting up Kilocode", path = ".ai/hooks/kilocode-symbolic-links.sh", only_if = {name = "include_kilocode", value = true}},
]

[[variables]]
default = "some-project"
name = "project_name"
prompt = "What is the name of this project?"
validation = "^([a-zA-Z][a-zA-Z0-9_-]+)$"

[[variables]]
default = "overview"
name = "project_overview"
prompt = "What is the project overview?"

[[variables]]
default = "Typescript"
name = "programming_language"
prompt = "What is the programming language do you want to use?"

[[variables]]
default = "Deno"
name = "programming_framework"
prompt = "What is the programming framework do you want to use?"

[[variables]]
choices = ["none", "postgres", "mysql", "sqlite", "mongodb"]
default = "none"
name = "database"
prompt = "Which database do you want to use?"

[[variables]]
default = false
name = "include_remembrances"
prompt = "Do you want to include Remembrances AI memory system?"

[[variables]]
default = "./remembrances_data"
name = "remembrances_db"
only_if = {name = "include_remembrances", value = true}
prompt = "Where is the Remembrances database? (enter if you set REMEMBRANCES_DB env variable)"

[[variables]]
default = false
name = "include_serena"
prompt = "Do you want to include Serena AI MCP assistance?"

[[variables]]
default = true
name = "include_kilocode"
prompt = "Do you want to include Kilocode configuration?"

[[variables]]
default = ""
name = "has_build_system"
prompt = "Has your project a build system?. Write the command to run it."

[[variables]]
default = ""
name = "has_tests"
prompt = "Has your project tests? If so, write the command to run them."
