description = "An AI-powered configuration for any project"
ignore = [
  "README.md",
  "template.toml",
]
kickstart_version = 1
name = "AI"

[[variables]]
default = "some-project"
name = "project_name"
prompt = "What is the name of this project?"
validation = "^([a-zA-Z][a-zA-Z0-9_-]+)$"

[[variables]]
default = "overview"
name = "project_overview"
prompt = "What is the project overview?"

[[variables]]
default = "Typescript"
name = "programming-language"
prompt = "What is the programming language do you want to use?"

[[variables]]
default = "Deno"
name = "programming-framework"
prompt = "What is the programming framework do you want to use?"

[[variables]]
choices = ["none", "postgres", "mysql", "sqlite", "mongodb"]
default = "postgres"
name = "database"
prompt = "Which database do you want to use?"
