description = "An AI-powered configuration for any project"
ignore = [
  "README.md",
  "template.toml",
]
kickstart_version = 1
name = "AI"

copy_without_render = [
  "*.sh",
]

post_gen_hooks = [
  {name = "setting up Serena", path = ".ai/hooks/index-serena.sh", only_if = {name = "use_docker", value = false}},
  {name = "setting up Kilocode", path = ".ai/hooks/kilocode-symbolic-links.sh", only_if = {name = "include_kilocode", value = true}},
]

[[variables]]
default = true
name = "use_docker"
prompt = "Do you want to use the Docker version of MCP's and you are running kickstart using docker?"

[[variables]]
default = "some-project"
name = "project_name"
prompt = "What is the name of this project?"
validation = "^([a-zA-Z][a-zA-Z0-9_-]+)$"

[[variables]]
default = "overview"
name = "project_overview"
prompt = "Whatistheprojectoverview?"

[[variables]]
default = "Typescript"
name = "programming_language"
prompt = "Whatistheprogramminglanguagedoyouwanttouse?"

[[variables]]
default = "Deno"
name = "programming_framework"
prompt = "Whatistheprogrammingframeworkdoyouwanttouse?"

[[variables]]
choices = ["none", "postgres", "mysql", "sqlite", "mongodb"]
default = "none"
name = "database"
prompt = "Whichdatabasedoyouwanttouse?"

[[variables]]
default = false
name = "include_remembrances"
prompt = "DoyouwanttoincludeRemembrancesAImemorysystem?"

[[variables]]
default = "./remembrances_data"
name = "remembrances_db"
only_if = {name = "include_remembrances", value = true}
prompt = "WhereistheRemembrancesdatabase?(enterifyousetREMEMBRANCES_DBenvvariable)"

[[variables]]
default = false
name = "include_serena"
prompt = "DoyouwanttoincludeSerenaAIMCPassistance?"

[[variables]]
default = true
name = "include_kilocode"
prompt = "DoyouwanttoincludeKilocodeconfiguration?"

[[variables]]
default = ""
name = "has_build_system"
prompt = "Hasyourprojectabuildsystem?.Writethecommandtorunit."

[[variables]]
default = ""
name = "has_tests"
prompt = "Hasyourprojecttests?Ifso,writethecommandtorunthem."
